/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                               ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                    ~
 ~                                                                               ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");               ~
 ~ you may not use this file except in compliance with the License.              ~
 ~ You may obtain a copy of the License at                                       ~
 ~                                                                               ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                              ~
 ~                                                                               ~
 ~ Unless required by applicable law or agreed to in writing, software           ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,             ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      ~
 ~ See the License for the specific language governing permissions and           ~
 ~ limitations under the License.                                                ~
 ~                                                                               ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.center.iterator;

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * An abstract iterator with computational properties. By extending this abstract iterator and implementing the
 * {@link #computeNext()} method to calculate the next node, iteration can be completed. When {@link #hasNext()} is
 * called, the node generated by {@link #computeNext()} is cached until {@link #next()} is called to retrieve it. When
 * there are no more nodes, {@code null} must be returned to indicate the end of iteration.
 *
 * @param <T> the type of elements returned by this iterator
 * @author Kimi Liu
 * @since Java 17+
 */
public abstract class ComputeIterator<T> implements Iterator<T> {

    /**
     * Constructs a new ComputeIterator. Utility class constructor for static access.
     */
    public ComputeIterator() {
    }

    /**
     * The next element to be returned by the iterator.
     */
    private T next;
    /**
     * A flag indicating if the iterator has been fully read.
     */
    private boolean finished;

    /**
     * Computes the next element. Implement this method to define how the next element is generated. When
     * {@link #hasNext()} is called, the element produced by this method is cached until {@link #next()} is called to
     * retrieve it. Return {@code null} to indicate that there are no more elements to iterate.
     *
     * @return the next element, or {@code null} if the iteration has no more elements
     */
    protected abstract T computeNext();

    /**
     * Returns {@code true} if the iteration has more elements. (In other words, returns {@code true} if {@link #next}
     * would return an element rather than throwing an exception.)
     *
     * @return {@code true} if the iteration has more elements
     */
    @Override
    public boolean hasNext() {
        if (null != next) {
            // The user has read a node but not used it yet.
            return true;
        } else if (finished) {
            // Iteration has finished.
            return false;
        }

        final T result = computeNext();
        if (null == result) {
            // No more new nodes, end iteration.
            this.finished = true;
            return false;
        } else {
            this.next = result;
            return true;
        }

    }

    /**
     * Returns the next element in the iteration.
     *
     * @return the next element in the iteration
     * @throws NoSuchElementException if the iteration has no more elements
     */
    @Override
    public T next() {
        if (!hasNext()) {
            throw new NoSuchElementException("No more lines");
        }

        final T result = this.next;
        // Clear the cache, indicating this node has been read, and compute a new node next time.
        this.next = null;
        return result;
    }

    /**
     * Resets the state for re-traversal.
     * <p>
     * Clears the 'finished' flag and the 'next' buffer, allowing the iterator to start over from the beginning.
     */
    public void reset() {
        this.finished = false;
        this.next = null;
    }

    /**
     * Manually finishes the iterator, typically used for closing operations. After calling this method,
     * {@link #hasNext()} will return {@code false} and {@link #next()} will throw {@link NoSuchElementException}.
     */
    public void finish() {
        this.finished = true;
        this.next = null;
    }

}
