/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                               ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                    ~
 ~                                                                               ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");               ~
 ~ you may not use this file except in compliance with the License.              ~
 ~ You may obtain a copy of the License at                                       ~
 ~                                                                               ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                              ~
 ~                                                                               ~
 ~ Unless required by applicable law or agreed to in writing, software           ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,             ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      ~
 ~ See the License for the specific language governing permissions and           ~
 ~ limitations under the License.                                                ~
 ~                                                                               ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
/**
 * Provides implementations for Message Authentication Code (MAC) algorithms.
 * <p>
 * MAC, or "Message Authentication Code," is a cryptographic checksum generated by a secret key. It is used to verify
 * the authenticity and integrity of a message.
 * </p>
 * <p>
 * HMAC, or "Hash-based Message Authentication Code," is a specific type of MAC that uses a cryptographic hash function
 * and a secret key. It is commonly used to verify messages exchanged between two parties who share a secret key. HMAC
 * can be used with any iterative cryptographic hash function, such as MD5 and SHA-1.
 * </p>
 *
 * <pre>
 *     {@code
 *         MacEngineFactory
 *               ||(creates)
 *           MacEngine----------------(wraps)-----------------> Mac
 *          _____|_______________                                |
 *         /                     \                              HMac
 *  JCEMacEngine             BCMacEngine
 *                            /        \
 *                   BCHMacEngine  CBCBlockCipherMacEngine
 *                                          |
 *                                     SM4MacEngine
 *
 * }
 * </pre>
 * <p>
 * This package encapsulates MAC algorithms implemented by both BouncyCastle and JCE. The {@code MacEngineFactory}
 * automatically creates the corresponding object based on the algorithm name.
 * </p>
 *
 * @author Kimi Liu
 * @since Java 17+
 */
package org.miaixz.bus.crypto.builtin.digest.mac;
