/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.spring.http;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import org.miaixz.bus.core.lang.Normal;
import org.miaixz.bus.core.lang.Symbol;
import org.miaixz.bus.core.lang.annotation.Ignore;
import org.miaixz.bus.core.lang.annotation.Include;
import org.miaixz.bus.core.xyz.ObjectKit;

import jakarta.persistence.Transient;

/**
 * An abstract base class for HTTP message converters that provides a unified and reusable logic for determining which
 * fields and classes should be skipped during JSON serialization.
 * <p>
 * This class encapsulates the common rules for handling annotations such as {@link Include} and {@link Transient}, as
 * well as Java's {@code transient} keyword and null/empty values. It is designed to be used by concrete converter
 * implementations for libraries like Fastjson, GSON, and Jackson to ensure consistent behavior.
 * </p>
 *
 * @author Kimi Liu
 * @since Java 21+
 */
public abstract class AbstractHttpMessageConverter implements HttpMessageConverter {

    /**
     * Determines if an entire class should be skipped during serialization.
     * <p>
     * This is a safeguard to prevent serialization of framework-generated or internal classes that are not part of the
     * user's domain model. By default, it skips synthetic classes (like proxies) and classes generated by frameworks
     * like CGLIB or Spring AOP.
     * </p>
     *
     * @param clazz The class to inspect. Can be {@code null}.
     * @return {@code true} if the class should be skipped, {@code false} otherwise.
     */
    public boolean isClassIgnored(Class<?> clazz) {
        if (clazz == null) {
            return false;
        }

        // Skip synthetic classes, which are often generated by the JVM or frameworks.
        if (clazz.isSynthetic()) {
            return true;
        }

        // Skip common proxy class patterns to avoid serializing framework internals.
        String className = clazz.getName();
        if (className.contains("$$EnhancerBySpringCGLIB$$") || className.contains("$Proxy")
                || className.contains("CGLIB$$")) {
            return true;
        }

        // By default, do not skip the class.
        return false;
    }

    /**
     * Determines if a field should be skipped during serialization based solely on its metadata (annotations and
     * modifiers). This method does not consider the field's actual value.
     * <p>
     * The logic is as follows, with priority given in order:
     * </p>
     * <ol>
     * <li>If a field is annotated with {@link Include}, it is <strong>never skipped</strong>, overriding all other
     * rules.</li>
     * <li>If a field is annotated with {@link Transient} OR has the {@code transient} modifier, it is <strong>always
     * skipped</strong>.</li>
     * <li>All other fields are <strong>not skipped</strong> by default.</li>
     * </ol>
     *
     * @param field The field to inspect. Can be {@code null}.
     * @return {@code true} if the field should be skipped, {@code false} otherwise.
     */
    protected static boolean isFieldIgnored(Field field) {
        if (field == null) {
            return false; // Default to not skipping if the field is unknown
        }

        // Rule 1: @Include has the highest priority and forces inclusion.
        if (field.isAnnotationPresent(Include.class)) {
            return false; // Do NOT skip
        }

        if (field.isAnnotationPresent(Ignore.class)) {
            return true; // DO skip
        }

        // Rule 2: @Transient and the 'transient' keyword force exclusion.
        if (field.isAnnotationPresent(Transient.class) || Modifier.isTransient(field.getModifiers())) {
            return true; // DO skip
        }

        // Rule 3: Default behavior is to not skip the field.
        return false;
    }

    /**
     * A private helper method to check if a value is considered "empty" for serialization purposes. An empty value is
     * defined as {@code null}, an empty string, or a string containing only whitespace.
     *
     * @param value The value to check.
     * @return {@code true} if the value is null, empty, or blank; {@code false} otherwise.
     */
    private static boolean isValueIgnored(Object value) {
        return ObjectKit.isEmpty(value) || Normal.EMPTY.equals(value) || Symbol.SPACE.equals(value);
    }

    /**
     * Determines if a field should be skipped during serialization by considering both its metadata (annotations,
     * modifiers) and its actual value.
     * <p>
     * This method first applies the annotation-based rules from {@link #isFieldIgnored(Field)}. If the field is not
     * skipped by those rules, it then checks the field's value.
     * </p>
     *
     * @param field The field to inspect. Can be {@code null}.
     * @param value The current value of the field. Can be {@code null}.
     * @return {@code true} if the field should be skipped, {@code false} otherwise.
     */
    protected static boolean shouldSkipField(Field field, Object value) {
        // First, apply the annotation and modifier checks.
        if (isFieldIgnored(field)) {
            return true;
        }

        // If not skipped by metadata, check the value.
        if (isValueIgnored(value)) {
            return true; // Skip fields with null, empty, or blank values.
        }

        // If not skipped by metadata or value, do not skip.
        return false;
    }

}
