/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.lang.reflect;

import java.lang.reflect.Member;

import org.miaixz.bus.core.lang.Assert;

/**
 * Represents a class member, providing access to class modifiers and other class-level information.
 * <p>
 * Example usage:
 * 
 * <pre>
 * ClassMember member = new ClassMember(String.class);
 * System.out.println(member.getModifiers());
 * </pre>
 *
 * @author Kimi Liu
 * @since Java 17+
 */
public class ClassMember implements Member {

    /**
     * The class represented by this {@code ClassMember} instance.
     */
    private final Class<?> clazz;

    /**
     * Constructs a new {@code ClassMember} instance for the given class.
     *
     * @param clazz The class to be represented. Must not be {@code null}.
     * @throws IllegalArgumentException if {@code clazz} is {@code null}.
     */
    public ClassMember(final Class<?> clazz) {
        this.clazz = Assert.notNull(clazz);
    }

    /**
     * Creates a new {@code ClassMember} instance for the given class using a static factory method.
     *
     * @param clazz The class to be represented. Must not be {@code null}.
     * @return A new {@code ClassMember} object.
     * @throws IllegalArgumentException if {@code clazz} is {@code null}.
     */
    public static ClassMember of(final Class<?> clazz) {
        return new ClassMember(clazz);
    }

    /**
     * Returns the {@code Class} object representing the class that declares this member. For a {@code ClassMember},
     * this is the class itself.
     *
     * @return The {@code Class} object representing the declaring class.
     */
    @Override
    public Class<?> getDeclaringClass() {
        return this.clazz;
    }

    /**
     * Returns the simple name of the underlying class represented by this {@code ClassMember}.
     *
     * @return The simple name of the class.
     */
    @Override
    public String getName() {
        return this.clazz.getName();
    }

    /**
     * Returns the Java language modifiers for the class represented by this {@code ClassMember}. The modifiers are
     * encoded in an integer, as specified by the {@link java.lang.reflect.Modifier} class.
     *
     * @return The integer representing the modifiers for this class.
     */
    @Override
    public int getModifiers() {
        return this.clazz.getModifiers();
    }

    /**
     * Determines if this class is a synthetic class. A synthetic class is one that is generated by the compiler and
     * does not appear in the source code.
     *
     * @return {@code true} if this class is synthetic; {@code false} otherwise.
     */
    @Override
    public boolean isSynthetic() {
        return this.clazz.isSynthetic();
    }

}
