Args = --initialize-at-build-time=org.miaixz.bus.crypto.Holder,org.bouncycastle \
  --initialize-at-run-time=org.bouncycastle.jcajce.provider.drbg.DRBG$Default,org.bouncycastle.jcajce.provider.drbg.DRBG$NonceAndIV \
  -H:AdditionalSecurityProviders=org.bouncycastle.jce.provider.BouncyCastleProvider
