/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.text.dfa;

import java.util.Set;

import org.miaixz.bus.core.xyz.SetKit;

/**
 * Utility class for handling stop characters, such as punctuation and whitespace, which are typically ignored during
 * text processing, especially in DFA-based algorithms.
 *
 * @author Kimi Liu
 * @since Java 21+
 */
public class StopChar {

    /**
     * A set of characters that are considered stop words or characters that do not require processing. This includes
     * various punctuation marks, symbols, and whitespace characters.
     */
    public static final Set<Character> STOP_WORD = SetKit.of(
            ' ',
            '\'',
            '、',
            '。',
            '·',
            'ˉ',
            'ˇ',
            '々',
            '—',
            '～',
            '‖',
            '…',
            '‘',
            '’',
            '“',
            '”',
            '〔',
            '〕',
            '〈',
            '〉',
            '《',
            '》',
            '「',
            '」',
            '『',
            '』',
            '〖',
            '〗',
            '【',
            '】',
            '±',
            '＋',
            '－',
            '×',
            '÷',
            '∧',
            '∨',
            '∑',
            '∏',
            '∪',
            '∩',
            '∈',
            '√',
            '⊥',
            '⊙',
            '∫',
            '∮',
            '≡',
            '≌',
            '≈',
            '∽',
            '∝',
            '≠',
            '≮',
            '≯',
            '≤',
            '≥',
            '∞',
            '∶',
            '∵',
            '∴',
            '∷',
            '♂',
            '♀',
            '°',
            '′',
            '〃',
            '℃',
            '＄',
            '¤',
            '￠',
            '￡',
            '‰',
            '§',
            '☆',
            '★',
            '〇',
            '○',
            '●',
            '◎',
            '◇',
            '◆',
            '□',
            '■',
            '△',
            '▽',
            '⊿',
            '▲',
            '▼',
            '◣',
            '◤',
            '◢',
            '◥',
            '▁',
            '▂',
            '▃',
            '▄',
            '▅',
            '▆',
            '▇',
            '█',
            '▉',
            '▊',
            '▋',
            '▌',
            '▍',
            '▎',
            '▏',
            '▓',
            '※',
            '→',
            '←',
            '↑',
            '↓',
            '↖',
            '↗',
            '↘',
            '↙',
            '〓',
            'ⅰ',
            'ⅱ',
            'ⅲ',
            'ⅳ',
            'ⅴ',
            'ⅵ',
            'ⅶ',
            'ⅷ',
            'ⅸ',
            'ⅹ',
            '①',
            '②',
            '③',
            '④',
            '⑤',
            '⑥',
            '⑦',
            '⑧',
            '⑨',
            '⑩',
            '⒈',
            '⒉',
            '⒊',
            '⒋',
            '⒌',
            '⒍',
            '⒎',
            '⒏',
            '⒐',
            '⒑',
            '⒒',
            '⒓',
            '⒔',
            '⒕',
            '⒖',
            '⒗',
            '⒘',
            '⒙',
            '⒚',
            '⒛',
            '⑴',
            '⑵',
            '⑶',
            '⑷',
            '⑸',
            '⑹',
            '⑺',
            '⑻',
            '⑼',
            '⑽',
            '⑾',
            '⑿',
            '⒀',
            '⒁',
            '⒂',
            '⒃',
            '⒄',
            '⒅',
            '⒆',
            '⒇',
            'Ⅰ',
            'Ⅱ',
            'Ⅲ',
            'Ⅳ',
            'Ⅴ',
            'Ⅵ',
            'Ⅶ',
            'Ⅷ',
            'Ⅸ',
            'Ⅹ',
            'Ⅺ',
            'Ⅻ',
            '！',
            '＃',
            '￥',
            '％',
            '＆',
            '（',
            '）',
            '＊',
            '，',
            '．',
            '／',
            '０',
            '１',
            '２',
            '３',
            '４',
            '５',
            '６',
            '７',
            '８',
            '９',
            '：',
            '；',
            '＜',
            '＝',
            '＞',
            '？',
            '＠',
            '〔',
            '＼',
            '〕',
            '＾',
            '＿',
            '‘',
            '｛',
            '｜',
            '｝',
            'Ρ',
            'Υ',
            'Φ',
            'Χ',
            'Ψ',
            'Ω',
            'α',
            'β',
            'γ',
            'δ',
            'ε',
            'ζ',
            'η',
            'θ',
            'ι',
            'κ',
            'λ',
            'μ',
            'ν',
            'ξ',
            'ο',
            'π',
            'ρ',
            'σ',
            'τ',
            'υ',
            'φ',
            'χ',
            'ψ',
            'ω',
            '（',
            '）',
            '＾',
            '﹊',
            '﹍',
            '╭',
            '╮',
            '╰',
            '╯',
            '',
            '_',
            '',
            '^',
            '（',
            '：',
            '！',
            '/',
            '\\',
            '\"',
            '<',
            '>',
            '`',
            '{',
            '}',
            '~',
            '(',
            ')',
            '-',
            '$',
            '@',
            '*',
            '&',
            '#',
            '卐',
            '㎎',
            '㎏',
            '㎜',
            '㎝',
            '㎞',
            '㎡',
            '㏄',
            '㏎',
            '㏑',
            '㏒',
            '㏕',
            '+',
            '=',
            '?',
            ':',
            '.',
            '!',
            ';',
            ']',
            '|',
            '%');

    /**
     * Checks if the given character is a stop character. Stop characters are typically ignored during text processing.
     *
     * @param ch The character to check.
     * @return {@code true} if the character is a whitespace character or present in the {@link #STOP_WORD} set,
     *         {@code false} otherwise.
     */
    public static boolean isStopChar(final char ch) {
        return Character.isWhitespace(ch) || STOP_WORD.contains(ch);
    }

    /**
     * Checks if the given character is not a stop character (i.e., it is a valid character for processing).
     *
     * @param ch The character to check.
     * @return {@code true} if the character is not a stop character, {@code false} otherwise.
     */
    public static boolean isNotStopChar(final char ch) {
        return !isStopChar(ch);
    }

}
