/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.center.date.culture;

/**
 * Represents the Five Elements (Wood, Fire, Earth, Metal, Water) in Chinese philosophy. This class extends
 * {@link Samsara} to manage a cyclical list of these entities.
 *
 * @author Kimi Liu
 * @since Java 21+
 */
public class Element extends Samsara {

    /**
     * Array of names for the Five Elements.
     */
    public static final String[] NAMES = { "木", "火", "土", "金", "水" };

    /**
     * Constructs an {@code Element} instance with the specified index.
     *
     * @param index The index of the element in the {@link #NAMES} array.
     */
    public Element(int index) {
        super(NAMES, index);
    }

    /**
     * Constructs an {@code Element} instance with the specified name.
     *
     * @param name The name of the element.
     */
    public Element(String name) {
        super(NAMES, name);
    }

    /**
     * Constructs an element from a custom element-name array and index.
     *
     * @param names the element names
     * @param index the index in the provided array
     */
    protected Element(String[] names, int index) {
        super(names, index);
    }

    /**
     * Constructs an element from a custom element-name array and name.
     *
     * @param names the element names
     * @param name  the element name
     */
    protected Element(String[] names, String name) {
        super(names, name);
    }

    /**
     * Creates an {@code Element} instance from its index.
     *
     * @param index The index of the element.
     * @return A new {@code Element} instance.
     */
    public static Element fromIndex(int index) {
        return new Element(index);
    }

    /**
     * Creates an {@code Element} instance from its name.
     *
     * @param name The name of the element.
     * @return A new {@code Element} instance.
     */
    public static Element fromName(String name) {
        return new Element(name);
    }

    /**
     * Gets the next {@code Element} in the cycle.
     *
     * @param n The number of steps to move forward or backward in the cycle.
     * @return The next {@code Element} instance.
     */
    public Element next(int n) {
        return fromIndex(nextIndex(n));
    }

    /**
     * Gets the element generated by this element.
     *
     * @return The reinforcing {@link Element}.
     */
    public Element getReinforce() {
        return next(1);
    }

    /**
     * Gets the element controlled by this element.
     *
     * @return The restraining {@link Element}.
     */
    public Element getRestrain() {
        return next(2);
    }

    /**
     * Gets the element that generates this element.
     *
     * @return The reinforced {@link Element}.
     */
    public Element getReinforced() {
        return next(-1);
    }

    /**
     * Gets the element that controls this element.
     *
     * @return The restrained {@link Element}.
     */
    public Element getRestrained() {
        return next(-2);
    }

    /**
     * Gets the corresponding {@link Direction} for this Element.
     *
     * @return The {@link Direction} associated with this Element.
     */
    public Direction getDirection() {
        return Direction.fromIndex(new int[] { 2, 8, 4, 6, 0 }[index]);
    }

}
