version: "@project.version@"

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%p]) [%t] - %highlight(%logger{40}:%L) : - %magenta(%m%n)"
    file: "%green(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%p]) - %highlight(%C:%L) : - %magenta(%m%n)"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 90

spring:
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: always