/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.text.escape;

import java.io.Serial;

import org.miaixz.bus.core.text.replacer.LookupReplacer;

/**
 * Unescapes characters for HTML 4.0. This class provides functionality to convert HTML 4.0 entity references back into
 * their original characters.
 *
 * <p>
 * It extends {@link XmlUnescape} to handle basic XML entities and adds support for ISO-8859-1 and extended HTML 4.0
 * entities.
 *
 * @author Kimi Liu
 * @since Java 17+
 */
public class Html4Unescape extends XmlUnescape {

    @Serial
    private static final long serialVersionUID = 2852236030759L;

    /**
     * Lookup table for ISO-8859-1 HTML unescape characters. This array is generated by inverting the
     * {@link Html4Escape#ISO8859_1_ESCAPE} array, mapping HTML entity references back to their original characters.
     */
    protected static final String[][] ISO8859_1_UNESCAPE = invert(Html4Escape.ISO8859_1_ESCAPE);
    /**
     * Lookup table for extended HTML 4.0 unescape characters. This array is generated by inverting the
     * {@link Html4Escape#HTML40_EXTENDED_ESCAPE} array, mapping HTML entity references back to their original
     * characters.
     */
    protected static final String[][] HTML40_EXTENDED_UNESCAPE = invert(Html4Escape.HTML40_EXTENDED_ESCAPE);

    /**
     * Constructs a new {@code Html4Unescape} instance. Initializes the unescape chain with basic XML unescaping,
     * followed by ISO-8859-1 and extended HTML 4.0 unescape lookup replacers.
     */
    public Html4Unescape() {
        super();
        addChain(new LookupReplacer(ISO8859_1_UNESCAPE));
        addChain(new LookupReplacer(HTML40_EXTENDED_UNESCAPE));
    }

}
