/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.core.text.escape;

import java.io.Serial;

import org.miaixz.bus.core.text.replacer.LookupReplacer;
import org.miaixz.bus.core.text.replacer.ReplacerChain;

/**
 * Unescapes special XML characters. This class provides functionality to convert XML entity references back into their
 * original characters.
 *
 * <p>
 * It unescapes the following XML entities:
 *
 * <ul>
 * <li>{@code &amp;} to {@code &} (ampersand)</li>
 * <li>{@code &lt;} to {@code <} (less than)</li>
 * <li>{@code &gt;} to {@code >} (greater than)</li>
 * <li>{@code &quot;} to {@code "} (double quote)</li>
 * <li>{@code &apos;} to {@code '} (single quote)</li>
 * </ul>
 * It also handles numeric entity unescaping.
 *
 * @author Kimi Liu
 * @since Java 21+
 */
public class XmlUnescape extends ReplacerChain {

    @Serial
    private static final long serialVersionUID = 2852236398787L;

    /**
     * Basic XML unescape lookup table. This array is generated by inverting the {@link XmlEscape#BASIC_ESCAPE} array,
     * mapping XML entity references back to their original characters.
     */
    protected static final String[][] BASIC_UNESCAPE = invert(XmlEscape.BASIC_ESCAPE);

    /**
     * Constructs a new {@code XmlUnescape} instance. Initializes the unescape chain with the basic XML unescape lookup
     * replacer and a {@link NumericEntityUnescaper} for handling numeric character references.
     */
    public XmlUnescape() {
        addChain(new LookupReplacer(BASIC_UNESCAPE));
        addChain(new NumericEntityUnescaper());
    }

    /**
     * Inverts a 2D string array by swapping the elements at index 0 and 1 within each inner array. This is typically
     * used to create an unescape lookup table from an escape lookup table.
     *
     * @param array The 2D string array to be inverted. Each inner array is expected to have at least two elements.
     * @return A new 2D string array where the first and second elements of each inner array are swapped.
     */
    public static String[][] invert(final String[][] array) {
        final String[][] newarray = new String[array.length][2];
        for (int i = 0; i < array.length; i++) {
            newarray[i][0] = array[i][1];
            newarray[i][1] = array[i][0];
        }
        return newarray;
    }

}
