/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.vortex.registry;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import org.miaixz.bus.cortex.Assets;
import org.miaixz.bus.cortex.Keying;
import org.miaixz.bus.cortex.Type;
import org.miaixz.bus.cortex.builtin.RegistryGenerator;
import org.miaixz.bus.logger.Logger;

/**
 * A specialized, in-memory registry for managing route {@link Assets}.
 * <p>
 * This registry stores one strongest runtime route key per asset and indexes all weaker candidates generated by the
 * shared {@link Keying} strategy. Registration and lookup therefore consume exactly the same candidate chain.
 * </p>
 *
 * @author Kimi Liu
 * @see AbstractRegistry
 * @see Assets
 * @since Java 21+
 */
public class AssetsRegistry extends AbstractRegistry<Assets> {

    /**
     * Route-key strategy used for canonical and compatibility key generation.
     */
    protected final Keying<Keying.RegistrySpec> keying;
    /**
     * Compatibility alias index from one route-key mode to the canonical route-key set.
     */
    private final Map<String, Set<String>> aliasIndex = new ConcurrentHashMap<>();
    /**
     * Reverse lookup from canonical route key to the registered alias keys.
     */
    private final Map<String, List<String>> keysByPrimary = new ConcurrentHashMap<>();

    /**
     * Constructs an {@code AssetsRegistry} and configures its key generation strategy.
     */
    public AssetsRegistry() {
        this(RegistryGenerator.INSTANCE);
    }

    /**
     * Constructs an {@code AssetsRegistry} with an explicit route-key strategy.
     *
     * @param keying route-key strategy
     */
    public AssetsRegistry(Keying<Keying.RegistrySpec> keying) {
        this.keying = keying == null ? RegistryGenerator.INSTANCE : keying;
        setKeyGenerator(asset -> this.keying.key(Keying.RegistrySpec.route(asset)));
    }

    /**
     * Returns the route-key strategy used by this registry.
     *
     * @return route-key strategy
     */
    public Keying<Keying.RegistrySpec> keying() {
        return keying;
    }

    /**
     * Registers an asset using the strongest route key and all compatible runtime aliases.
     *
     * @param item asset to register
     */
    @Override
    public void register(Assets item) {
        if (keyGenerator == null) {
            throw new IllegalStateException("Key generator has not been set. Call setKeyGenerator in the constructor.");
        }
        if (item == null) {
            return;
        }
        Keying.RegistrySpec spec = Keying.RegistrySpec.route(item);
        String primary = keyGenerator.apply(item);
        if (!accept(primary, spec, null)) {
            return;
        }
        super.register(primary, item);
        List<String> keys = keying.keys(spec);
        List<String> previous = keysByPrimary.put(primary, keys);
        if (previous != null) {
            for (String key : previous) {
                aliasIndex.computeIfPresent(key, (ignored, targets) -> {
                    targets.remove(primary);
                    return targets.isEmpty() ? null : targets;
                });
            }
        }
        for (String key : keys) {
            Set<String> targets = aliasIndex.computeIfAbsent(key, ignored -> ConcurrentHashMap.newKeySet());
            targets.add(primary);
            if (targets.size() > 1) {
                Logger.warn(false, "Vortex", "Assets route key '{}' is ambiguous across {}", key, targets);
            }
        }
    }

    /**
     * Updates an asset by replacing any existing registration associated with the supplied key.
     *
     * @param key  canonical or compatibility key
     * @param item updated asset
     */
    @Override
    public void update(String key, Assets item) {
        if (item == null) {
            return;
        }
        String resolvedPrimary = resolvePrimary(key);
        if (resolvedPrimary == null) {
            return;
        }
        Keying.RegistrySpec spec = Keying.RegistrySpec.route(item);
        String primary = keying.key(spec);
        if (!accept(primary, spec, resolvedPrimary)) {
            return;
        }
        destroy(resolvedPrimary);
        register(item);
    }

    /**
     * Removes one asset registration together with all of its compatibility aliases.
     *
     * @param key canonical or compatibility key
     */
    @Override
    public void destroy(String key) {
        String resolvedPrimary = resolvePrimary(key);
        if (resolvedPrimary == null) {
            return;
        }
        List<String> keys = keysByPrimary.remove(resolvedPrimary);
        if (keys != null) {
            for (String alias : keys) {
                aliasIndex.computeIfPresent(alias, (ignored, targets) -> {
                    targets.remove(resolvedPrimary);
                    return targets.isEmpty() ? null : targets;
                });
            }
        }
        super.destroy(resolvedPrimary);
    }

    /**
     * Clears both the canonical registry storage and the compatibility alias indexes.
     *
     * @return refresh completion signal
     */
    @Override
    public reactor.core.publisher.Mono<Void> refresh() {
        return reactor.core.publisher.Mono.fromRunnable(() -> {
            aliasIndex.clear();
            keysByPrimary.clear();
        }).then(super.refresh());
    }

    /**
     * Resolves one route asset from the supplied route specification.
     *
     * @param spec route dimensions
     * @return matching asset or {@code null}
     */
    public Assets get(Keying.RegistrySpec spec) {
        if (spec == null || !spec.routable()) {
            return null;
        }
        for (String routeKey : keying.keys(spec)) {
            if (routeKey == null) {
                continue;
            }
            Set<String> targets = aliasIndex.get(routeKey);
            if (targets == null || targets.isEmpty()) {
                continue;
            }
            Assets resolved = null;
            for (String primary : targets) {
                Assets candidate = super.get(primary);
                if (candidate == null) {
                    continue;
                }
                if (resolved != null) {
                    Logger.warn(false, "Vortex", "Assets route key '{}' is ambiguous across {}", routeKey, targets);
                    return null;
                }
                resolved = candidate;
            }
            if (resolved != null) {
                return resolved;
            }
        }
        return null;
    }

    /**
     * Resolves one route asset using all supported runtime dimensions.
     *
     * @param type      route type, optional
     * @param namespace route namespace, optional
     * @param appId     application identifier, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, Type type, String appId, String method, String version, Integer verb) {
        return get(Keying.RegistrySpec.route(namespace, type, appId, method, version, verb));
    }

    /**
     * Resolves one route asset without application scope.
     *
     * @param type      route type, optional
     * @param namespace route namespace, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, Type type, String method, String version, Integer verb) {
        return get(Keying.RegistrySpec.route(namespace, type, null, method, version, verb));
    }

    /**
     * Resolves one route asset using namespace and application scope only.
     *
     * @param namespace route namespace, optional
     * @param appId     application identifier, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, String appId, String method, String version, Integer verb) {
        return get(Keying.RegistrySpec.route(namespace, null, appId, method, version, verb));
    }

    /**
     * Resolves one route asset without application or type scope.
     *
     * @param namespace route namespace, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, String method, String version, Integer verb) {
        return get(Keying.RegistrySpec.route(namespace, null, null, method, version, verb));
    }

    /**
     * Resolves one route asset from method, version, and verb without requiring callers to know namespace or type.
     *
     * @param method  route method
     * @param version route version
     * @param verb    numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String method, String version, Integer verb) {
        return get(Keying.RegistrySpec.route(null, null, null, method, version, verb));
    }

    /**
     * Resolves one canonical or compatibility key to the associated asset.
     *
     * @param key canonical or compatibility route key
     * @return matching asset or {@code null}
     */
    @Override
    public Assets get(String key) {
        Assets direct = super.get(key);
        if (direct != null) {
            return direct;
        }
        String primary = resolvePrimary(key);
        if (primary == null || primary.equals(key)) {
            return null;
        }
        return super.get(primary);
    }

    /**
     * Returns whether one incoming asset can be written without breaking strongest-key ownership.
     *
     * @param primary         incoming strongest route key
     * @param spec            incoming route specification
     * @param retainedPrimary current primary to keep on update, or {@code null} during fresh registration
     * @return {@code true} when the write may proceed
     */
    protected boolean accept(String primary, Keying.RegistrySpec spec, String retainedPrimary) {
        if (spec == null || !spec.routable()) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because method/version/verb are required for runtime route keys: {}",
                    spec);
            return false;
        }
        if (primary == null) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because the strongest runtime route key is missing: {}",
                    spec);
            return false;
        }
        Assets existing = super.get(primary);
        if (existing == null || primary.equals(retainedPrimary)) {
            return true;
        }
        if (retainedPrimary == null) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because primary route key '{}' is already owned and incoming route '{}' was rejected",
                    primary,
                    spec);
        } else {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped update because primary route key '{}' is already owned and source '{}' was kept",
                    primary,
                    retainedPrimary);
        }
        return false;
    }

    /**
     * Resolves one canonical primary key from either a primary key or one unique compatibility alias.
     *
     * @param key canonical or compatibility key
     * @return resolved canonical primary key or {@code null}
     */
    protected String resolvePrimary(String key) {
        if (key == null) {
            return null;
        }
        if (super.get(key) != null) {
            return key;
        }
        Set<String> targets = aliasIndex.get(key);
        if (targets == null || targets.isEmpty() || targets.size() != 1) {
            return null;
        }
        return targets.iterator().next();
    }

}
