/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.vortex.registry;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import org.miaixz.bus.core.lang.Normal;
import org.miaixz.bus.core.lang.Symbol;
import org.miaixz.bus.core.xyz.StringKit;
import org.miaixz.bus.cortex.Assets;
import org.miaixz.bus.cortex.Keying;
import org.miaixz.bus.cortex.Type;
import org.miaixz.bus.cortex.builtin.RegistryGenerator;
import org.miaixz.bus.cortex.registry.RegistryAssets;
import org.miaixz.bus.logger.Logger;
import org.miaixz.bus.vortex.Args;

import reactor.core.publisher.Mono;

/**
 * A specialized, in-memory registry for managing route {@link Assets}.
 * <p>
 * This registry stores one strongest runtime route key per asset and indexes all weaker candidates generated by the
 * shared {@link Keying} strategy. Registration and lookup therefore consume exactly the same candidate chain. MCP
 * service assets use the same route index as other protocols and are matched by path-segment-safe longest prefix
 * lookup.
 * </p>
 *
 * @see AbstractRegistry
 * @see Assets
 * @author Kimi Liu
 * @since Java 21+
 */
public class AssetsRegistry extends AbstractRegistry<Assets> {

    /**
     * Route-key strategy used for canonical and compatibility key generation.
     */
    protected final Keying<Keying.RegistrySpec> keying;

    /**
     * Compatibility alias index from one route-key mode to the canonical route-key set.
     */
    private final Map<String, Set<String>> aliasIndex = new ConcurrentHashMap<>();

    /**
     * Reverse lookup from canonical route key to the registered alias keys.
     */
    private final Map<String, List<String>> keysByPrimary = new ConcurrentHashMap<>();

    /**
     * Constructs an {@code AssetsRegistry} and configures its key generation strategy.
     */
    public AssetsRegistry() {
        this(RegistryGenerator.INSTANCE);
    }

    /**
     * Constructs an {@code AssetsRegistry} with an explicit route-key strategy.
     *
     * @param keying route-key strategy
     */
    public AssetsRegistry(Keying<Keying.RegistrySpec> keying) {
        this.keying = keying == null ? RegistryGenerator.INSTANCE : keying;
        setKeyGenerator(asset -> this.keying.key(Keying.RegistrySpec.route(asset)));
    }

    /**
     * Registers an asset using the strongest route key and all compatible runtime aliases.
     * <p>
     * MCP assets are registered as route assets. Their {@code method} field is the public service prefix, and their
     * {@code url} field is the downstream Streamable HTTP base URL.
     *
     * @param item asset to register
     */
    @Override
    public void register(Assets item) {
        if (keyGenerator == null) {
            throw new IllegalStateException("Key generator has not been set. Call setKeyGenerator in the constructor.");
        }
        if (item == null) {
            return;
        }
        if (isMcp(item)) {
            String method = normalizeMcpRouteMethod(item.getMethod());
            if (method == null || StringKit.isBlank(item.getUrl())) {
                Logger.warn(
                        false,
                        "Vortex",
                        "MCP route skipped registration: assetId={}, method={}, version={}, verb={}, url={}",
                        item.getId(),
                        item.getMethod(),
                        item.getVersion(),
                        item.getVerb(),
                        item.getUrl());
                return;
            }
            item.setMethod(method);
        }
        Keying.RegistrySpec spec = Keying.RegistrySpec.route(item);
        String primary = keyGenerator.apply(item);
        if (!accept(primary, spec, null)) {
            return;
        }
        super.register(primary, item);
        List<String> keys = keying.keys(spec);
        List<String> previous = keysByPrimary.put(primary, keys);
        if (previous != null) {
            for (String key : previous) {
                aliasIndex.computeIfPresent(key, (ignored, targets) -> {
                    targets.remove(primary);
                    return targets.isEmpty() ? null : targets;
                });
            }
        }
        for (String key : keys) {
            Set<String> targets = aliasIndex.computeIfAbsent(key, ignored -> ConcurrentHashMap.newKeySet());
            targets.add(primary);
            if (targets.size() > 1) {
                Logger.warn(false, "Vortex", "Assets route key '{}' is ambiguous across {}", key, targets);
            }
        }
    }

    /**
     * Updates an asset by replacing any existing registration associated with the supplied key.
     * <p>
     * MCP assets follow the same route-key update path as other protocols.
     *
     * @param key  canonical or compatibility key
     * @param item updated asset
     */
    @Override
    public void update(String key, Assets item) {
        if (item == null) {
            return;
        }
        String resolvedPrimary = resolvePrimary(key);
        if (resolvedPrimary == null) {
            return;
        }
        Keying.RegistrySpec spec = Keying.RegistrySpec.route(item);
        String primary = keying.key(spec);
        if (!accept(primary, spec, resolvedPrimary)) {
            return;
        }
        destroy(resolvedPrimary);
        register(item);
    }

    /**
     * Removes one asset registration together with all of its compatibility aliases.
     * <p>
     * The supplied key may be a canonical route key or one unique compatibility alias.
     *
     * @param key canonical or compatibility key
     */
    @Override
    public void destroy(String key) {
        String resolvedPrimary = resolvePrimary(key);
        if (resolvedPrimary == null) {
            return;
        }
        List<String> keys = keysByPrimary.remove(resolvedPrimary);
        if (keys != null) {
            for (String alias : keys) {
                aliasIndex.computeIfPresent(alias, (ignored, targets) -> {
                    targets.remove(resolvedPrimary);
                    return targets.isEmpty() ? null : targets;
                });
            }
        }
        super.destroy(resolvedPrimary);
    }

    /**
     * Removes one asset registration by asset instance.
     * <p>
     * Removal is delegated to key-based destruction so compatibility aliases are cleaned consistently.
     *
     * @param item asset to remove
     */
    @Override
    public void destroy(Assets item) {
        super.destroy(item);
    }

    /**
     * Clears both the canonical registry storage and the compatibility alias indexes.
     *
     * @return refresh completion signal
     */
    @Override
    public Mono<Void> refresh() {
        return Mono.fromRunnable(() -> {
            aliasIndex.clear();
            keysByPrimary.clear();
        }).then(super.refresh());
    }

    /**
     * Resolves one canonical or compatibility key to the associated asset.
     *
     * @param key canonical or compatibility route key
     * @return matching asset or {@code null}
     */
    @Override
    public Assets get(String key) {
        Assets direct = super.get(key);
        if (direct != null) {
            return direct;
        }
        String primary = resolvePrimary(key);
        if (primary == null || primary.equals(key)) {
            return null;
        }
        return super.get(primary);
    }

    /**
     * Resolves one route asset using all supported runtime dimensions.
     *
     * @param type      route type, optional
     * @param namespace route namespace, optional
     * @param appId     application identifier, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, Type type, String appId, String method, String version, Integer verb) {
        RouteMatch match = get(Keying.RegistrySpec.route(namespace, type, appId, method, version, verb));
        return match == null ? null : match.assets();
    }

    /**
     * Resolves one route asset without application scope.
     *
     * @param type      route type, optional
     * @param namespace route namespace, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, Type type, String method, String version, Integer verb) {
        RouteMatch match = get(Keying.RegistrySpec.route(namespace, type, null, method, version, verb));
        return match == null ? null : match.assets();
    }

    /**
     * Resolves one route asset using namespace and application scope only.
     *
     * @param namespace route namespace, optional
     * @param appId     application identifier, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, String appId, String method, String version, Integer verb) {
        RouteMatch match = get(Keying.RegistrySpec.route(namespace, null, appId, method, version, verb));
        return match == null ? null : match.assets();
    }

    /**
     * Resolves one route asset without application or type scope.
     *
     * @param namespace route namespace, optional
     * @param method    route method
     * @param version   route version
     * @param verb      numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String namespace, String method, String version, Integer verb) {
        RouteMatch match = get(Keying.RegistrySpec.route(namespace, null, null, method, version, verb));
        return match == null ? null : match.assets();
    }

    /**
     * Resolves one route asset from method, version, and verb without requiring callers to know namespace or type.
     *
     * @param method  route method
     * @param version route version
     * @param verb    numeric verb code
     * @return matching asset or {@code null}
     */
    public Assets get(String method, String version, Integer verb) {
        RouteMatch match = get(Keying.RegistrySpec.route(null, null, null, method, version, verb));
        return match == null ? null : match.assets();
    }

    /**
     * Resolves one route together with the remaining request path.
     * <p>
     * Exact route-key lookup is attempted first. MCP requests additionally support path-segment-safe longest prefix
     * matching, and the returned {@link RouteMatch#remainingPath()} is calculated from the same winning route prefix so
     * downstream executors do not repeat route matching.
     *
     * @param spec runtime route dimensions
     * @return matching route or {@code null}
     */
    public RouteMatch get(Keying.RegistrySpec spec) {
        if (spec == null || !spec.routable()) {
            return null;
        }
        RouteMatch exact = exactRouteMatch(spec);
        if (exact != null) {
            return exact;
        }
        return prefixRouteMatch(spec);
    }

    /**
     * Resolves one route by the ordered exact route-key chain.
     *
     * @param spec runtime route dimensions
     * @return exact route match or {@code null}
     */
    private RouteMatch exactRouteMatch(Keying.RegistrySpec spec) {
        String requestPath = spec.methodPart();
        for (String routeKey : keying.keys(spec)) {
            if (routeKey == null) {
                continue;
            }
            Set<String> primaryKeys = aliasIndex.get(routeKey);
            if (primaryKeys == null || primaryKeys.isEmpty()) {
                continue;
            }
            Assets exact = null;
            for (String primaryKey : primaryKeys) {
                Assets candidate = super.get(primaryKey);
                if (candidate == null) {
                    continue;
                }
                if (exact != null) {
                    Logger.warn(false, "Vortex", "Assets route key '{}' is ambiguous across {}", routeKey, primaryKeys);
                    return null;
                }
                exact = candidate;
            }
            if (exact != null) {
                return new RouteMatch(exact, remainingPath(requestPath, exact.getMethod()));
            }
        }
        return null;
    }

    /**
     * Resolves one route by path-prefix matching and strongest route-key fallback level.
     *
     * @param spec runtime route dimensions
     * @return prefix route match or {@code null}
     */
    private RouteMatch prefixRouteMatch(Keying.RegistrySpec spec) {
        String requestPath = spec.methodPart();
        if (!Args.isMcpRequest(requestPath)) {
            return null;
        }
        RouteMatch best = null;
        int bestLevel = Integer.MAX_VALUE;
        int bestPrefixLength = -1;
        for (Assets candidate : getAll()) {
            if (!isMcp(candidate)) {
                continue;
            }
            if (!Objects.equals(candidate.getVersion(), spec.versionPart())
                    || !Objects.equals(candidate.getVerb(), spec.verbPart())) {
                continue;
            }
            String routePrefix = candidate.getMethod();
            String remainingPath = remainingPath(requestPath, routePrefix);
            if (remainingPath == null) {
                continue;
            }
            Integer level = routeMatchLevel(spec, candidate);
            if (level == null) {
                continue;
            }
            int prefixLength = routePrefix.length();
            if (level < bestLevel || (level == bestLevel && prefixLength > bestPrefixLength)) {
                best = new RouteMatch(candidate, remainingPath);
                bestLevel = level;
                bestPrefixLength = prefixLength;
            } else if (level == bestLevel && prefixLength == bestPrefixLength) {
                Logger.warn(
                        false,
                        "Vortex",
                        "MCP route prefix '{}' is ambiguous for namespace={}, type={}, appId={}, method={}, version={}, verb={}",
                        routePrefix,
                        spec.namespacePart(),
                        spec.typeKeyPart(),
                        spec.appIdPart(),
                        spec.methodPart(),
                        spec.versionPart(),
                        spec.verbPart());
                return null;
            }
        }
        return best;
    }

    /**
     * Returns whether one incoming asset can be written without breaking strongest-key ownership.
     * <p>
     * A route asset must provide enough dimensions to build a runtime route key. On update, the retained primary key is
     * allowed to keep ownership while duplicate writes from other assets are rejected.
     *
     * @param primary         incoming strongest route key
     * @param spec            incoming route specification
     * @param retainedPrimary current primary to keep on update, or {@code null} during fresh registration
     * @return {@code true} when the write may proceed
     */
    protected boolean accept(String primary, Keying.RegistrySpec spec, String retainedPrimary) {
        if (spec == null || !spec.routable()) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because method/version/verb are required for runtime route keys: {}",
                    spec);
            return false;
        }
        if (primary == null) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because the strongest runtime route key is missing: {}",
                    spec);
            return false;
        }
        Assets existing = super.get(primary);
        if (existing == null || primary.equals(retainedPrimary)) {
            return true;
        }
        if (retainedPrimary == null) {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped registration because primary route key '{}' is already owned and incoming route '{}' was rejected",
                    primary,
                    spec);
        } else {
            Logger.warn(
                    false,
                    "Vortex",
                    "Assets skipped update because primary route key '{}' is already owned and source '{}' was kept",
                    primary,
                    retainedPrimary);
        }
        return false;
    }

    /**
     * Returns the route-key strategy used by this registry.
     *
     * @return route-key strategy
     */
    public Keying<Keying.RegistrySpec> keying() {
        return keying;
    }

    /**
     * Calculates the route-key fallback level at which a wildcard candidate matches the request.
     *
     * @param request   runtime request route
     * @param candidate registered wildcard candidate
     * @return one-based match level, or {@code null} when no route-key candidate matches
     */
    private Integer routeMatchLevel(Keying.RegistrySpec request, Assets candidate) {
        Keying.RegistrySpec requested = Keying.RegistrySpec.route(
                request.namespacePart(),
                request.typePart(),
                request.appIdPart(),
                candidate.getMethod(),
                request.versionPart(),
                request.verbPart());
        List<String> requestKeys = keying.keys(requested);
        List<String> candidateKeys = keying.keys(Keying.RegistrySpec.route(candidate));
        for (int i = 0; i < requestKeys.size(); i++) {
            if (candidateKeys.contains(requestKeys.get(i))) {
                return i + 1;
            }
        }
        return null;
    }

    /**
     * Returns the remaining request path for one already matched route prefix.
     *
     * @param requestPath request route path
     * @param routePrefix registered route path prefix
     * @return remaining path, empty string for exact match, or {@code null} when the prefix does not match
     */
    private String remainingPath(String requestPath, String routePrefix) {
        if (StringKit.isBlank(routePrefix) || StringKit.isBlank(requestPath)) {
            return null;
        }
        if (requestPath.equals(routePrefix)) {
            return Normal.EMPTY;
        }
        if (requestPath.startsWith(routePrefix + Symbol.SLASH)) {
            return requestPath.substring(routePrefix.length());
        }
        return null;
    }

    /**
     * Returns whether the asset is an MCP registry asset using the MCP protocol code.
     *
     * @param asset asset to inspect
     * @return {@code true} when the asset belongs to MCP routing
     */
    private boolean isMcp(Assets asset) {
        return asset != null && Type.MCP.is(RegistryAssets.typeOf(asset))
                && Integer.valueOf(Args.PROTOCOL_MCP).equals(asset.getProtocol());
    }

    /**
     * Normalizes and validates the public MCP service prefix stored in {@code assets.method}.
     *
     * @param method public MCP service prefix
     * @return normalized route method, or {@code null} when invalid
     */
    private String normalizeMcpRouteMethod(String method) {
        if (StringKit.isBlank(method)) {
            return null;
        }
        String normalized = method.trim();
        while (normalized.length() > Args.MCP_PATH_PREFIX.length() + 1 && normalized.endsWith(Symbol.SLASH)) {
            normalized = normalized.substring(0, normalized.length() - 1);
        }
        if (!normalized.startsWith(Args.MCP_PATH_PREFIX + Symbol.SLASH)) {
            return null;
        }
        String servicePath = normalized.substring((Args.MCP_PATH_PREFIX + Symbol.SLASH).length());
        if (StringKit.isBlank(servicePath) || servicePath.contains(Symbol.STAR)
                || servicePath.contains(Symbol.DOUBLE_DOT) || servicePath.contains(Symbol.FORWARDSLASH)) {
            return null;
        }
        return normalized;
    }

    /**
     * Resolves one canonical primary key from either a primary key or one unique compatibility alias.
     *
     * @param key canonical or compatibility key
     * @return resolved canonical primary key or {@code null}
     */
    protected String resolvePrimary(String key) {
        if (key == null) {
            return null;
        }
        if (super.get(key) != null) {
            return key;
        }
        Set<String> targets = aliasIndex.get(key);
        if (targets == null || targets.isEmpty() || targets.size() != 1) {
            return null;
        }
        return targets.iterator().next();
    }

    /**
     * Matched runtime route asset and the remaining request path produced by route matching.
     *
     * @param assets        matched route asset
     * @param remainingPath remaining path after the matched route prefix, or an empty string for an exact match
     * @author Kimi Liu
     * @since Java 21+
     */
    public record RouteMatch(Assets assets, String remainingPath) {

    }

}
