/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/
package org.miaixz.bus.vortex.registry;

import org.miaixz.bus.vortex.magic.Limiter;

/**
 * Default rate limiter registry implementation, providing registration and management functionalities for rate limiter
 * configurations ({@link Limiter}) based on {@link AbstractRegistry}.
 *
 * @author Justubborn
 * @since Java 21+
 */
public class LimiterRegistry extends AbstractRegistry<Limiter> {

    /**
     * Constructs a {@code LimiterRegistry} and sets the key generation strategy. The key for a limiter is generated by
     * concatenating its IP, method, and version.
     */
    public LimiterRegistry() {
        setKeyGenerator(limiter -> limiter.getIp() + limiter.getMethod() + limiter.getVersion());
    }

    /**
     * Retrieves a rate limiter configuration based on its IP address, method name, and version number.
     *
     * @param ip      The IP address.
     * @param method  The method name.
     * @param version The version number.
     * @return The matching {@link Limiter} object, or {@code null} if no configuration is found.
     */
    public Limiter get(String ip, String method, String version) {
        return this.get(ip + method + version);
    }

}
