name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd ../bus-core && mvn clean
          cd ../bus-logger && mvn clean
          cd ../bus-setting && mvn clean
          cd ../bus-opencv && mvn clean
          cd ../bus-proxy && mvn clean
          cd ../bus-cron && mvn clean
          cd ../bus-crypto && mvn clean
          cd ../bus-extra && mvn clean
          cd ../bus-cache && mvn clean
          cd ../bus-gitlab && mvn clean
          cd ../bus-health && mvn clean
          cd ../bus-http && mvn clean
          cd ../bus-goalie && mvn clean
          cd ../bus-image && mvn clean
          cd ../bus-limiter && mvn clean
          cd ../bus-mapper && mvn clean
          cd ../bus-notify && mvn clean
          cd ../bus-oauth && mvn clean
          cd ../bus-office && mvn clean
          cd ../bus-pager && mvn clean
          cd ../bus-parent && mvn clean
          cd ../bus-pay && mvn clean
          cd ../bus-sensitive && mvn clean
          cd ../bus-shade && mvn clean
          cd ../bus-socket && mvn clean
          cd ../bus-storage && mvn clean
          cd ../bus-tracer && mvn clean
          cd ../bus-validate && mvn clean
          cd ../bus-base && mvn clean
          cd ../bus-starter && mvn clean
          cd ../bus-bom && mvn clean
          cd ../bus-all && mvn clean
          cd ../bus-parent && mvn clean




